export * from './slices/auth'
export * from './slices/deposit'
export * from './slices/dialog'
export * from './slices/games'
export * from './slices/level'
export * from './slices/on-boarding'
export * from './slices/profile'
export * from './slices/register'
export * from './slices/wallet'
export * from './slices/withdraw'

export * from './slices/v2/deposit.store'
export * from './slices/v2/wallet.store'
export * from './slices/v2/withdraw.store'
export * from './slices/v2/dialog.store'
